
# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : jayashreeramanblogs
author :
  name : Jayashree Raman
  email : jramanuw@gmail.com
  github : jayashreeraman
  twitter : do_it_herselfer

# NOTE: Replacing this next line with your own URL
production_url : https://jayashreeraman.github.io/jayashreeramanblogs

# Tell Github to use the kramdown markdown interpreter
# (see https://help.github.com/articles/migrating-your-pages-site-from-maruku)
markdown: kramdown

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0

# NOTE: Replace this next line with your own URL, likely with username.github.io
BASE_PATH : https://jayashreeraman.github.io/jayashreeramanblogs

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
archive_path: nil
categories_path : nil
tags_path : nil
atom_path : nil
rss_path : nil

